//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.2
//     from Assets/InputSystem/ProbeMetaControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/InputSystem/ProbeMetaControls.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @ProbeMetaControls: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @ProbeMetaControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""ProbeMetaControls"",
    ""maps"": [
        {
            ""name"": ""ProbeMetaControl"",
            ""id"": ""49e6acce-5ef4-408e-a8fa-bc4787423202"",
            ""actions"": [
                {
                    ""name"": ""NextProbe"",
                    ""type"": ""Button"",
                    ""id"": ""108721c3-f35f-49f2-9241-7e0216cc018f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PrevProbe"",
                    ""type"": ""Button"",
                    ""id"": ""e5f1fc89-463d-4706-8808-b52f36a687a8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchAxisMode"",
                    ""type"": ""Button"",
                    ""id"": ""1d360e34-a12a-492a-8082-001ccd73c45d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""98c5463b-d1a0-4efa-a3f6-5e8429d25d84"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NextProbe"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1fe4a68a-d755-474e-ab44-5e374bb15777"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NextProbe"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d00557a5-21a2-4dd4-b7bb-5947865ff4f8"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrevProbe"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""25de11d4-83e3-4b5e-90cf-5ae605c2ecc2"",
                    ""path"": ""<Keyboard>/n"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrevProbe"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d3c8b135-b617-4544-a621-f79112d4ad87"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchAxisMode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8e0fb31b-16bc-425f-b1de-f8c1fadca630"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchAxisMode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // ProbeMetaControl
        m_ProbeMetaControl = asset.FindActionMap("ProbeMetaControl", throwIfNotFound: true);
        m_ProbeMetaControl_NextProbe = m_ProbeMetaControl.FindAction("NextProbe", throwIfNotFound: true);
        m_ProbeMetaControl_PrevProbe = m_ProbeMetaControl.FindAction("PrevProbe", throwIfNotFound: true);
        m_ProbeMetaControl_SwitchAxisMode = m_ProbeMetaControl.FindAction("SwitchAxisMode", throwIfNotFound: true);
    }

    ~@ProbeMetaControls()
    {
        UnityEngine.Debug.Assert(!m_ProbeMetaControl.enabled, "This will cause a leak and performance issues, ProbeMetaControls.ProbeMetaControl.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // ProbeMetaControl
    private readonly InputActionMap m_ProbeMetaControl;
    private List<IProbeMetaControlActions> m_ProbeMetaControlActionsCallbackInterfaces = new List<IProbeMetaControlActions>();
    private readonly InputAction m_ProbeMetaControl_NextProbe;
    private readonly InputAction m_ProbeMetaControl_PrevProbe;
    private readonly InputAction m_ProbeMetaControl_SwitchAxisMode;
    /// <summary>
    /// Provides access to input actions defined in input action map "ProbeMetaControl".
    /// </summary>
    public struct ProbeMetaControlActions
    {
        private @ProbeMetaControls m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public ProbeMetaControlActions(@ProbeMetaControls wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "ProbeMetaControl/NextProbe".
        /// </summary>
        public InputAction @NextProbe => m_Wrapper.m_ProbeMetaControl_NextProbe;
        /// <summary>
        /// Provides access to the underlying input action "ProbeMetaControl/PrevProbe".
        /// </summary>
        public InputAction @PrevProbe => m_Wrapper.m_ProbeMetaControl_PrevProbe;
        /// <summary>
        /// Provides access to the underlying input action "ProbeMetaControl/SwitchAxisMode".
        /// </summary>
        public InputAction @SwitchAxisMode => m_Wrapper.m_ProbeMetaControl_SwitchAxisMode;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_ProbeMetaControl; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="ProbeMetaControlActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(ProbeMetaControlActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="ProbeMetaControlActions" />
        public void AddCallbacks(IProbeMetaControlActions instance)
        {
            if (instance == null || m_Wrapper.m_ProbeMetaControlActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ProbeMetaControlActionsCallbackInterfaces.Add(instance);
            @NextProbe.started += instance.OnNextProbe;
            @NextProbe.performed += instance.OnNextProbe;
            @NextProbe.canceled += instance.OnNextProbe;
            @PrevProbe.started += instance.OnPrevProbe;
            @PrevProbe.performed += instance.OnPrevProbe;
            @PrevProbe.canceled += instance.OnPrevProbe;
            @SwitchAxisMode.started += instance.OnSwitchAxisMode;
            @SwitchAxisMode.performed += instance.OnSwitchAxisMode;
            @SwitchAxisMode.canceled += instance.OnSwitchAxisMode;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="ProbeMetaControlActions" />
        private void UnregisterCallbacks(IProbeMetaControlActions instance)
        {
            @NextProbe.started -= instance.OnNextProbe;
            @NextProbe.performed -= instance.OnNextProbe;
            @NextProbe.canceled -= instance.OnNextProbe;
            @PrevProbe.started -= instance.OnPrevProbe;
            @PrevProbe.performed -= instance.OnPrevProbe;
            @PrevProbe.canceled -= instance.OnPrevProbe;
            @SwitchAxisMode.started -= instance.OnSwitchAxisMode;
            @SwitchAxisMode.performed -= instance.OnSwitchAxisMode;
            @SwitchAxisMode.canceled -= instance.OnSwitchAxisMode;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="ProbeMetaControlActions.UnregisterCallbacks(IProbeMetaControlActions)" />.
        /// </summary>
        /// <seealso cref="ProbeMetaControlActions.UnregisterCallbacks(IProbeMetaControlActions)" />
        public void RemoveCallbacks(IProbeMetaControlActions instance)
        {
            if (m_Wrapper.m_ProbeMetaControlActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="ProbeMetaControlActions.AddCallbacks(IProbeMetaControlActions)" />
        /// <seealso cref="ProbeMetaControlActions.RemoveCallbacks(IProbeMetaControlActions)" />
        /// <seealso cref="ProbeMetaControlActions.UnregisterCallbacks(IProbeMetaControlActions)" />
        public void SetCallbacks(IProbeMetaControlActions instance)
        {
            foreach (var item in m_Wrapper.m_ProbeMetaControlActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ProbeMetaControlActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="ProbeMetaControlActions" /> instance referencing this action map.
    /// </summary>
    public ProbeMetaControlActions @ProbeMetaControl => new ProbeMetaControlActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "ProbeMetaControl" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="ProbeMetaControlActions.AddCallbacks(IProbeMetaControlActions)" />
    /// <seealso cref="ProbeMetaControlActions.RemoveCallbacks(IProbeMetaControlActions)" />
    public interface IProbeMetaControlActions
    {
        /// <summary>
        /// Method invoked when associated input action "NextProbe" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnNextProbe(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "PrevProbe" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPrevProbe(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SwitchAxisMode" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSwitchAxisMode(InputAction.CallbackContext context);
    }
}
